# Generated by Django 3.2.10 on 2022-02-22 06:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('format', models.SmallIntegerField(choices=[(1, 'pdf'), (2, 'docx'), (3, 'doc'), (4, 'xlsx'), (5, 'xls'), (6, 'jpeg'), (7, 'png'), (8, 'jpg')], default=1)),
                ('document_type', models.SmallIntegerField(choices=[(0, 'Загруженный'), (1, 'Сгенерированный')], default=0)),
                ('status', models.SmallIntegerField(choices=[(0, 'Новый'), (1, 'Активный'), (2, 'Архив')], default=1)),
                ('name', models.CharField(max_length=200)),
                ('body', models.BinaryField()),
                ('num_pages', models.IntegerField(blank=True, null=True)),
                ('size', models.BigIntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('downloaded', models.DateTimeField(blank=True, null=True)),
                ('link_stage', models.SmallIntegerField(choices=[(0, 'Загружается'), (1, 'Загружен'), (2, 'Удален')], default=0)),
                ('preview_stage', models.SmallIntegerField(choices=[(0, 'Загружается'), (1, 'Загружен'), (2, 'Удален')], default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.SmallIntegerField(choices=[(1, 'Конвертировать'), (2, 'Разделить'), (3, 'Объединить')])),
                ('status', models.SmallIntegerField(choices=[(0, 'Новая'), (1, 'В процессе'), (2, 'Успешно'), (3, 'Ошибка')], default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='OperationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_source', models.BooleanField(default=True, verbose_name='Это исходный документ?')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operation_ids', to='pdf.document')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_ids', to='pdf.operation')),
            ],
        ),
    ]
