# Generated by Django 3.2.10 on 2022-02-22 06:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('surname', models.CharField(blank=True, max_length=250, null=True)),
                ('patronymic', models.CharField(blank=True, max_length=250, null=True)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('login', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=200, null=True)),
                ('email_confirmed', models.BooleanField(default=False, verbose_name='Почта подтверждена?')),
                ('phone_confirmed', models.BooleanField(default=False, verbose_name='Телефон подтвержден?')),
                ('status', models.IntegerField(choices=[(0, 'Новый'), (1, 'Активный'), (2, 'Заблокированный'), (3, 'Удаленный')], default=1)),
                ('tariff', models.IntegerField(choices=[(0, 'Бесплатный'), (1, 'Премиум')], default=0)),
                ('role', models.IntegerField(choices=[(10, 'Администратор'), (1, 'Авторизованный пользователь'), (0, 'Анонимный пользователь')])),
                ('salt', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('password_updated', models.DateTimeField(blank=True, null=True)),
                ('tariff_updated', models.DateTimeField(blank=True, null=True)),
                ('auth_user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('profile', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.profile')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(blank=True, max_length=250, null=True)),
                ('push_token', models.CharField(blank=True, max_length=250, null=True)),
                ('maker', models.CharField(blank=True, max_length=200, null=True)),
                ('model_name', models.CharField(blank=True, max_length=100, null=True)),
                ('factory_number', models.CharField(blank=True, max_length=100, null=True)),
                ('series_number', models.CharField(blank=True, max_length=100, null=True)),
                ('operation_system', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='users.user')),
            ],
        ),
    ]
