# Generated by Django 3.2.10 on 2022-03-06 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tariff_finished',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='tariff',
            field=models.IntegerField(choices=[(0, 'Бесплатный'), (1, 'Премиум на месяц'), (2, 'Премиум на три месяца'), (3, 'Премиум на год')], default=0),
        ),
    ]
