# Generated by Django 3.2.10 on 2022-02-22 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=25)),
                ('text', models.TextField()),
                ('status', models.PositiveSmallIntegerField()),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('log', models.TextField(blank=True, default=None, null=True)),
                ('external_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActivationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=200)),
                ('code_type', models.IntegerField(choices=[(0, 'Email'), (1, 'Телефон')])),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activation_codes', to='users.user')),
            ],
            options={
                'verbose_name': 'Код активации',
                'verbose_name_plural': 'Коды активации',
                'db_table': 'activation_codes',
                'ordering': ('-timestamp',),
            },
        ),
    ]
